# Generated by Django 4.2.24 on 2026-02-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About Filip Merčep", max_length=200),
                ),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "intro_text",
                    models.TextField(help_text="Main introduction paragraph"),
                ),
                ("biography", models.TextField(help_text="Detailed biography")),
                (
                    "philosophy_quote",
                    models.TextField(
                        blank=True, help_text="Optional quote for philosophy section"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-year", "order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("year_start", models.IntegerField(blank=True, null=True)),
                ("year_end", models.IntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["order", "-year_end"],
            },
        ),
        migrations.CreateModel(
            name="Ensemble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="youtube_embed",
            field=models.CharField(
                blank=True,
                help_text="YouTube video ID only (e.g., 'dQw4w9WgXcQ' from youtube.com/watch?v=dQw4w9WgXcQ)",
                max_length=200,
            ),
        ),
    ]
